SELECT
	ALUN.RA AS RA,
	PESS.NOME AS NOME,
	PESS.CPF AS CPF,
	PESS.TELEFONE1 AS TELEFONE,
	PESS.EMAIL AS EMAIL,
	PESS.CIDADE AS CIDADE,
	PESS.ESTADO AS ESTADO,
	COLI.CODCOLIGADA AS CODCOLIGADA,
	COLI.NOME AS NOMECOLIGADA,
	COLI.CGC AS CNPJCOLIGADA,
	IMAG.IMAGEM AS IMAGEMCOLIGADA
FROM
	PPESSOA AS PESS (NOLOCK)
INNER JOIN
	SALUNO AS ALUN (NOLOCK) ON ALUN.CODPESSOA = PESS.CODIGO
INNER JOIN
	GCOLIGADA AS COLI (NOLOCK) ON COLI.CODCOLIGADA = ALUN.CODCOLIGADA
INNER JOIN
	GIMAGEM AS IMAG (NOLOCK) ON IMAG.ID = COLI.IDIMAGEM